# Setup
name: The "Q" -Pediatric Position Holder
title: The "Q" - Pediatric Position Holder
tagline: A one-piece radiolucent child medical positioning aid.
description: 'The Pediatric Position Holder is a revolutionary new pediatric child friendly device which is effective, safe, simple and versatile. The Pediatric Position Holder standardizes the process of immobilization, offering consistency across all modes of care for the infant and child.'
baseurl: ""
paginate: 1
locale: "en"

url: https://childrenssafetyimmobilizer.com/

# About/contact
author:
  name: Max Quattromani
  url: maxquattromani.com

#### Under the Hood Stuff #####
theme: jekyll-theme-cayman

google_analytics: UA-50387096-21

github:
  is_project_page: false

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
